name: Announcements workflow

on:
  release:
    types: [published]
  workflow_run:
    workflows: [AndroidMixMod workflow]
    types:
      - completed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Send telegram message on release
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Новая версия: ${{ github.ref_name }}
            
            https://github.com/${{ github.repository }}/releases/latest/
            
            #Download_APK
